using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using DG.Tweening;

namespace PersonalValue
{
    public class DragPrefabUn : MonoBehaviour, IBeginDragHandler, IDragHandler, IEndDragHandler, IPointerClickHandler
    {
        private RectTransform rectTransform;
        private CanvasGroup canvasGroup;
        private Vector3 offset;
        public DropBoxPriority dropBox;
        public DropBoxPriority formDropBox;
        public DragDropCard dragDropCard;
        public GameObject cardGroup;
        public Color dragColor;

    void Awake()
    {
        rectTransform = GetComponent<RectTransform>();
        canvasGroup = GetComponent<CanvasGroup>();
    }

    public void OnBeginDrag(PointerEventData eventData)
    {
        transform.SetParent(transform.root);
        canvasGroup.blocksRaycasts = false;
        offset = rectTransform.position - Camera.main.ScreenToWorldPoint(eventData.position);
        dropBox = null;
    }

    public void OnDrag(PointerEventData eventData)
    {
        Vector3 newPosition = Camera.main.ScreenToWorldPoint(eventData.position) + offset;
        rectTransform.position = new Vector3(newPosition.x, newPosition.y, rectTransform.position.z);
    }

    public void OnEndDrag(PointerEventData eventData)
    {
        canvasGroup.blocksRaycasts = true;
    }
    public void OnPointerClick(PointerEventData eventData)
    {
      
    }

    public void SetCardToBox()
    {
        LevelManager levelManager = GameManager.Instance.levelManager;
       if(dropBox != null)
       {

        if(dropBox == formDropBox) 
        {
             Hide();
        }
        else
        {
          
          //‡∏ñ‡πâ‡∏≤‡∏¢‡πâ‡∏≤‡∏¢‡πÑ‡∏õ dropBox ‡∏≠‡∏±‡∏ô‡∏ß‡πà‡∏≤‡∏á
          if(dropBox.cardName_Stage4 == null)
          {
            //Dropbox ‡∏≠‡∏±‡∏ô‡πÉ‡∏´‡∏°‡πà
            dropBox.cardName_Stage4 = formDropBox.cardName_Stage4;
            dropBox.transform.GetChild(0).GetComponent<Image>().sprite = formDropBox.cardName_Stage4.picture;

            //Dropbox ‡∏≠‡∏±‡∏ô‡πÄ‡∏î‡∏¥‡∏°
            formDropBox.cardName_Stage4 = null;
            formDropBox.transform.GetChild(0).GetComponent<Image>().sprite = GameManager.Instance.cardDatabaseSO.nullSprite;
            
            Hide();
            Debug.Log("‡∏ß‡πà‡∏≤‡∏á");
            return;
          }
          //‡∏ñ‡πâ‡∏≤‡∏¢‡πâ‡∏≤‡∏¢‡πÑ‡∏õ dropBox ‡∏≠‡∏±‡∏ô‡πÑ‡∏°‡πà‡∏ß‡πà‡∏≤‡∏á ‡∏™‡∏•‡∏±‡∏ö‡∏Å‡∏±‡∏ô
          if(dropBox.cardName_Stage4 != null)
          {
            Debug.Log("‡∏™‡∏•‡∏±‡∏ö");
            // üîÅ ‡πÄ‡∏Å‡πá‡∏ö‡∏Ç‡πâ‡∏≠‡∏°‡∏π‡∏•‡∏Ç‡∏≠‡∏á dropBox ‡πÉ‡∏´‡∏°‡πà‡πÑ‡∏ß‡πâ‡∏ä‡∏±‡πà‡∏ß‡∏Ñ‡∏£‡∏≤‡∏ß
            CardDataSO tempCard = dropBox.cardName_Stage4;

            // ‚úÖ ‡∏™‡∏•‡∏±‡∏ö‡∏Ç‡πâ‡∏≠‡∏°‡∏π‡∏• DropBox ‡πÉ‡∏´‡∏°‡πà ‚Üí ‡πÉ‡∏™‡πà‡∏Ç‡πâ‡∏≠‡∏°‡∏π‡∏•‡∏à‡∏≤‡∏Å‡πÄ‡∏î‡∏¥‡∏° (formDropBox)
            dropBox.cardName_Stage4 = formDropBox.cardName_Stage4;
            dropBox.transform.GetChild(0).GetComponent<Image>().sprite = formDropBox.cardName_Stage4.picture;

            // ‚úÖ ‡πÉ‡∏™‡πà tempCard ‡∏Å‡∏•‡∏±‡∏ö‡πÑ‡∏õ‡∏ó‡∏µ‡πà‡∏Å‡∏•‡πà‡∏≠‡∏á‡πÄ‡∏î‡∏¥‡∏°
            formDropBox.cardName_Stage4 = tempCard;
            formDropBox.transform.GetChild(0).GetComponent<Image>().sprite = tempCard.picture;

            Hide();
          }
        }
       }
    }
    
    public void Hide()
    {
        dropBox = null;
        formDropBox = null;
        this.gameObject.SetActive(false);
    }
       private void OnTriggerEnter2D(Collider2D collision)
        {
            if(collision.tag == "Menu")
            {
                collision.GetComponent<DropBoxPriority>().img.GetComponent<Image>().color = dragColor;
                dropBox = collision.GetComponent<DropBoxPriority>();
            }

            if(collision.tag == "CardGroup")
            {
                collision.GetComponent<Image>().color = dragColor;
                cardGroup = collision.gameObject;
            }
        }

        private void OnTriggerExit2D(Collider2D collision)
        {
            if(collision.tag == "Menu")
            {
                collision.GetComponent<DropBoxPriority>().img.GetComponent<Image>().color = Color.white;
                dropBox = null;
            }

            if(collision.tag == "CardGroup")
            {
                collision.GetComponent<Image>().color = Color.white;
                cardGroup = null;
            }
        }
    }
}
